### ISSUE TITLE
add to Paradox Mods?

### ISSUE THREAD

**Issue by shayanz23** [tduck973564/trafficreductionremover#1]
Hi, is there any chance of this mod being added to the official Paradox Mods?

**Comment by fesdonomist** [comment]
At some point I'll port it and add some configuration options

**Comment by fesdonomist** [comment]
https://mods.paradoxplaza.com/mods/76836/Windows

Ported, should work. Will be on Github soon.

**Comment by fesdonomist** [comment]
https://github.com/tduck973564/TrafficSimulationAdjuster/
